config:
  registries:
    - name: AmazonECR
      api_url: https://576607007321.dkr.ecr.us-east-1.amazonaws.com
      prefix: 576607007321.dkr.ecr.us-east-1.amazonaws.com
      ping: yes
      default: true
      insecure: false
      credentials: ext:/scripts/ecr-login.sh
      credsexpire: 12h
  git:
    user: "argocd-image-updater"
    email: "tokaelmaadawy@gmail.com"
    credentials:
      - url: "https://github.com/tokaashawky/GP_ArgoCD.git"
        usernameSecret:
          name: git-creds
          key: username
        passwordSecret:
          name: git-creds
          key: password

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      export HOME=/tmp
      aws ecr get-authorization-token \
        --region us-east-1 \
        --output text \
        --query 'authorizationData[].authorizationToken' | base64 -d
rbac:
  create: true

serviceAccount:
  create: true
  name: image-updater-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::576607007321:role/ImageUpdaterAccessRole


