apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: app
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 576607007321.dkr.ecr.us-east-1.amazonaws.com/gitops-gp-ecr:1.1
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"

            - name: MYSQL_HOST
              value: mysql-release.app.svc.cluster.local

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret 
                  key: username

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret 
                  key: mysql-password
                  
            - name: MYSQL_DATABASE
              value: mydatabase

            - name: REDIS_HOST
              value: redis-release-master.app.svc.cluster.local

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
