apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 576607007321.dkr.ecr.us-east-1.amazonaws.com/gitops-gp-ecr:1.1
          ports:
            - containerPort: 3000