apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: app
spec:
  selector:
    app: nodejs-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
