config:
  registries: 
    - name: ECR
      api_url: https://576607007321.dkr.ecr.us-east-1.amazonaws.com/gitops-gp-ecr
      prefix: 576607007321.dkr.ecr.us-east-1.amazonaws.com/gitops-gp-ecr
      credentials: ext:/scripts/auth.sh
      credsexpire: 12h
      ping: yes
      default: true
      insecure: false
  images:
    - name: 576607007321.dkr.ecr.us-east-1.amazonaws.com/gitops-gp-ecr
      alias: nodeapp

  logLevel: "info"

  git:
    writeBackMethod: "git"
    gitUser: "Toka_Argo_Image_Updater"
    gitEmail: "tokaelmaadawy@gmail.com"
    credentials:
      - url: https://github.com/tokaashawky
        usernameSecret:
          name: argocd-image-updater-creds
          key: username
        passwordSecret:
          name: argocd-image-updater-creds
          key: password

authScripts: 
  enabled: true
  scripts:
    auth.sh: |
      #!/bin/sh
      HOME=/tmp aws ecr --region us-east-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

serviceAccount:
  name: argo-image-updater
  create: true
